import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';
import { classifyAsset, fileToUrl } from '../sw/shared.js';

/**
 * Bump when the worker's caching logic changes in a way that makes previously
 * stored entries wrong. Activating a worker with a new version wipes the
 * content caches; a plain content deploy only drops what actually changed.
 */
const SW_VERSION = 1;

export type ManifestEntry = { url: string; hash: string; size: number };

export type OfflineManifest = {
  buildId: string;
  version: number;
  mode: 'prod' | 'dev';
  langs: string[];
  shell: ManifestEntry[];
  pages: ManifestEntry[];
  media: ManifestEntry[];
};

const hashOf = (data: string | Buffer): string =>
  createHash('sha256').update(data).digest('base64url').slice(0, 16);

const byUrl = (a: ManifestEntry, b: ManifestEntry): number => a.url.localeCompare(b.url);

/**
 * shared.js is written as a plain ES module so Vitest can cover it, but the
 * worker is a classic script: the two files are concatenated with the leading
 * `export` keywords removed. Anything else module-shaped is a mistake and
 * fails the build rather than shipping a broken worker.
 */
/** The only module syntax that survives the `export` keyword being removed. */
const INLINEABLE = /^export (?:const|let|function|async function|class) /;

export const stripExports = (source: string): string => {
  for (const line of source.match(/^\s*(?:import|export)\b.*$/gm) ?? []) {
    if (INLINEABLE.test(line)) continue;
    throw new Error(
      `[offline] src/sw/shared.js must only use \`export const\`/\`export function\` ` +
        `declarations — cannot inline: ${line.trim()}`,
    );
  }
  return source.replace(/^export /gm, '');
};

/**
 * Baked into the worker next to the manifest. `null` switches the worker's
 * reporter off entirely — that is what a missing .env or a missing SENTRY_DSN
 * resolves to, and what `astro dev` always gets.
 */
export type SentryConfig = { dsn: string; environment: string; release: string };

export const assembleWorker = (
  shared: string,
  worker: string,
  manifest: OfflineManifest,
  sentry: SentryConfig | null = null,
): string =>
  [
    '// Generated by src/integrations/offline.ts — do not edit.',
    '// Sources: src/sw/shared.js + src/sw/worker.js',
    `const MANIFEST = ${JSON.stringify(manifest)};`,
    `const SENTRY_CONFIG = ${JSON.stringify(sentry)};`,
    stripExports(shared),
    worker,
  ].join('\n');

const walk = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true });
  const found = await Promise.all(
    entries.map((entry) => {
      const full = path.join(dir, entry.name);
      return entry.isDirectory() ? walk(full) : Promise.resolve([full]);
    }),
  );
  return found.flat();
};

export const buildManifest = async (
  outDir: string,
  langs: string[],
): Promise<OfflineManifest> => {
  const shell: ManifestEntry[] = [];
  const pages: ManifestEntry[] = [];
  const media: ManifestEntry[] = [];

  for (const file of await walk(outDir)) {
    const relative = path.relative(outDir, file).split(path.sep).join('/');
    const url = fileToUrl(relative);
    const kind = classifyAsset(url);
    if (kind === 'skip') continue;

    const contents = await readFile(file);
    const entry: ManifestEntry = { url, hash: hashOf(contents), size: contents.byteLength };
    (kind === 'shell' ? shell : kind === 'page' ? pages : media).push(entry);
  }

  shell.sort(byUrl);
  pages.sort(byUrl);
  media.sort(byUrl);

  const buildId = hashOf(
    [...shell, ...pages, ...media].map((entry) => `${entry.url}:${entry.hash}`).join('\n'),
  );

  return { buildId, version: SW_VERSION, mode: 'prod', langs, shell, pages, media };
};

/**
 * Dev-only route enumeration. `astro dev` has no build output to scan and does
 * not expand dynamic routes ahead of a request, so the page list is derived
 * from the same content the routes are generated from. It exists purely so the
 * offline toggle is testable on the dev server — production always scans dist/.
 */
const devPages = async (srcDir: string, langs: string[]): Promise<ManifestEntry[]> => {
  const listDir = async (dir: string): Promise<string[]> => {
    try {
      return await readdir(dir);
    } catch {
      return [];
    }
  };

  const episodes = [
    ...new Set(
      (await listDir(path.join(srcDir, 'data', 'podcasts')))
        .filter((name) => name.endsWith('.json') && !name.endsWith('.terms.json'))
        .map((name) => name.replace(/\.[a-z]{2}\.json$/, '')),
    ),
  ].sort();

  const urls = ['/', '/subtitles/', '/yaml/'];

  for (const lang of langs) {
    const posts = (await listDir(path.join(srcDir, 'content', 'blog', lang)))
      .filter((name) => name.endsWith('.md'))
      .map((name) => name.replace(/\.md$/, ''))
      .sort();

    urls.push(`/${lang}/`, `/${lang}/blog/`, `/${lang}/podcasts/`, `/${lang}/offline/`);
    urls.push(...posts.map((slug) => `/${lang}/blog/${slug}/`));
    urls.push(...episodes.map((slug) => `/${lang}/podcasts/${slug}/`));
  }

  return urls.map((url) => ({ url, hash: 'dev', size: 0 }));
};

export const offline = (options: { sentry?: SentryConfig } = {}): AstroIntegration => {
  // An empty DSN is the off switch, not a broken config.
  const sentry = options.sentry?.dsn ? options.sentry : null;
  let langs: string[] = [];
  let srcDir = '';

  const readSources = async (): Promise<{ shared: string; worker: string }> => {
    const [shared, worker] = await Promise.all([
      readFile(path.join(srcDir, 'sw', 'shared.js'), 'utf8'),
      readFile(path.join(srcDir, 'sw', 'worker.js'), 'utf8'),
    ]);
    return { shared, worker };
  };

  return {
    name: 'offline',
    hooks: {
      'astro:config:done': ({ config }) => {
        langs = (config.i18n?.locales ?? []).map((locale) =>
          typeof locale === 'string' ? locale : locale.path,
        );
        srcDir = fileURLToPath(config.srcDir);
      },

      'astro:server:setup': ({ server }) => {
        server.middlewares.use((req, res, next) => {
          if ((req.url ?? '').split('?')[0] !== '/sw.js') return next();

          void (async () => {
            const { shared, worker } = await readSources();
            const manifest: OfflineManifest = {
              buildId: 'dev',
              version: SW_VERSION,
              mode: 'dev',
              langs,
              shell: [],
              pages: await devPages(srcDir, langs),
              media: [],
            };
            res.setHeader('content-type', 'text/javascript; charset=utf-8');
            res.setHeader('cache-control', 'no-cache');
            // Never the Sentry config: the dev server must not report.
            res.end(assembleWorker(shared, worker, manifest));
          })();
        });
      },

      'astro:build:done': async ({ dir, logger }) => {
        const outDir = fileURLToPath(dir);
        const manifest = await buildManifest(outDir, langs);
        const { shared, worker } = await readSources();
        await writeFile(
          path.join(outDir, 'sw.js'),
          assembleWorker(shared, worker, manifest, sentry),
          'utf8',
        );

        const bytes = [...manifest.shell, ...manifest.pages, ...manifest.media].reduce(
          (total, entry) => total + entry.size,
          0,
        );
        logger.info(
          `sw.js built ${manifest.buildId} — ${manifest.shell.length} shell, ` +
            `${manifest.pages.length} pages, ${manifest.media.length} media ` +
            `(${(bytes / 1048576).toFixed(1)} MB total)`,
        );
      },
    },
  };
};
